### ISSUE TITLE
Confused on how imports work

### ISSUE THREAD

**Issue by extreme4all** [DavidVujic/python-polylith-example-uv#3]
Hey, i'm pretty confused on how imports work in this scenario, i can't wrap my head around it, can you help me?
https://github.com/DavidVujic/python-polylith-example-uv/blob/ac4e86849d4be010daa1519bd87289630fa4ff7b/bases/example/message_api/core.py#L2-L3

i'm looking forward to understanding this cause this is really what i need

**Comment by DavidVujic** [comment]
Hi @extreme4all, `example` is the top namespace in this repo. All the code in the _bases_ and _components_ share the same top namespace.

In `database` and `schema` is an `__init__.py` where a selection of code is "exported" (this is just standard Python):
```
from example.database.core import Base, engine

__all__ = ["Base", "engine"]
```

Your dev environment is aware of the _bases_ and _components_ from the config of the top-level _pyproject.toml_. When you build a _wheel_ or an _sdist_ for an individual project, the folder structure in the wheel/sdist will be just like if it was a single-project repo:

```shell
pyproject.toml
README.md
...
example/
    database/
        __init__.py
        core.py
        ...
```

The way this works is that the `hatch-polylith-bricks` build hook will read the contents of the `[tool.polylith.bricks]` section in the project-specific `pyproject.toml` and feed that to the uv/hatchling build process.

__NOTE__: the `database` code in the example repo is (too) simple. In a real world scenario you probably want proper DB Session handling and such.

**Comment by extreme4all** [comment]
Hey @DavidVujic , thanks for your explanation, i further looked into it and just rephrasing to make sure my understanding is correct. Please correct my statement if needed.

the dev-mode-dirs is a hatch configuration that adds the directories to the Python's search path. This means that if i import `from example` it actually takes `components/example`, `bases/example` & `development/example` and `./example` into scope
interpreted from https://hatch.pypa.io/1.9/config/build/#dev-mode

from `./pyproject.toml`
```toml
[tool.hatch.build]
dev-mode-dirs = ["components", "bases", "development", "."]
```
beyond this, there is just the normal explicit module export control in python, importing with the `__init__.py` using `__all__ = []` 

from`projects/message_fastapi_project/pyproject.toml`
```toml
[tool.hatch.build.targets.wheel]
packages = ["example"]
```
this builds on the `./pyproject.toml` targetting the "example" in the "dev-mode-dirs"

**Comment by DavidVujic** [comment]
The first part, yes! That's exactly how it works.

The projects `pyproject.toml` doesn't deal with the top-level `dev-mode-dirs`. The `packages = ["example"]` need to be there, to define the source code path when building the wheel. Otherwise, Hatch and uv will fail with an error. Just before the actual building of a wheel or sdist, the Hatch build hook that is added in the project-specific `pyproject.toml` will append paths to the Hatch-specific `force include` feature. Hatch will copy the paths into a local file structure (and that is why it will need the `packages` definition).

The `[tool.polylith.bricks]` is basically the same thing as [force-include](https://hatch.pypa.io/latest/config/build/#forced-inclusion) in Hatch. I added the Polylith-feature in the config to not lock-in to only support Hatch. PDM has a similar, but different way of defining the paths, and the `tool.polylith.bricks` will wrap both ways. There's also Maturin, that is very different from both Hatch and PDM, but will work with the Polylith configuration in the toml files too.

The Polylith tool uses the underlying Package management tool (Hatch, uv, PDM, Poetry ...) as much as possible. I didn't want to reinvent already existing features 😄

**Comment by extreme4all** [comment]
somehow i may still not understand it properly, when i clone your repo pylance etc works fine but when i make my own repo following the guides it doesn't :(

**Comment by DavidVujic** [comment]
Could it be something missing in any of the `pyproject.toml` files?

The top-level toml should have this:
```toml
[tool.hatch.build]
dev-mode-dirs = ["components", "bases", "development", "."]
```

The projects `pyproject.toml` files should not have the dev-mode-dirs defined. But they need this:
(note the "hatch-polylith-bricks" added in the _requires_)
```toml
[build-system]
requires = ["hatchling", "hatch-polylith-bricks"]
build-backend = "hatchling.build"
```

You will need to run `uv sync` once to make uv add the dev-mode paths to the virtual environment. Also, for IDE integration, make sure to have a local venv (and not a venv outside of the repo/workspace).

**Comment by extreme4all** [comment]
okay i got it fixed now my mistake was in `./pyproject.toml` the build-system should be at the top
 ```toml
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
 ```

**Comment by extreme4all** [comment]
okay i think i more or less understand it, i'll play with the design hopefully it works that would be great i'm a bit annoyed that i had to duplicate pydantic models & dataclasses all over the place, and i think this should solve that!

**Comment by DavidVujic** [comment]
Great!

There's some also some info at the [Discussions forum](https://github.com/DavidVujic/python-polylith/discussions) of the Polylith repo. You are also very much welcome to share your feedback, questions and ideas there!
